qkniep/alpenglow

.github/workflows/rust.yml, src/network/simulated/core.rs, test.sh
`symmetric` and `asymmetric` are doing latency measurements and require in essence a dedicated core to have a high chance of succeeding.  This PR sets things up so that on CI, they run separately from the rest of the tests and while running, they have a high chance of not getting interrupted by other tests.  
The PR also refactors some of the code into functions to help with code reuse.
=> fix: apply a bandage to help with some flaky tests

src/consensus.rs
I haven't done a proper investigation if this is dangerous but it seems like we do not need need to hold the two locks at the same time so minor refactoring.
=> fix: do not hold blockstore lock while holding the pool lock

src/network/simulated/core.rs, src/network/simulated/token_bucket.rs, test.sh
This test is starting to fail on github some times.  Making is sequential might help.
Also adds minor comments to other sequential tests.
=> chore: make extreme_rate a sequential test

src/shredder.rs, src/shredder/reed_solomon.rs
- moves reed-solomon stuff into its own module
- introduces different error types to organise the errors a bit more
=> refactor: organise `shredder.rs` a bit

src/consensus/produce_block.rs
Deconstructing the slice ensures that if we add new fields in the slice, the compiler will help us in remembering to update the tests.
=> nit: deconstruct slice in some tests

benches/disseminator.rs, benches/network.rs, benches/shredder.rs, src/bin/performance_test.rs, src/consensus.rs, src/consensus/blockstore.rs, src/consensus/blockstore/slot_block_data.rs, src/consensus/cert.rs, src/consensus/epoch_info.rs, src/consensus/pool.rs, src/consensus/pool/parent_ready_tracker.rs, src/consensus/pool/parent_ready_tracker/parent_ready_state.rs, src/consensus/pool/slot_state.rs, src/consensus/produce_block.rs, src/consensus/vote.rs, src/consensus/votor.rs, src/disseminator/rotor.rs, src/disseminator/trivial.rs, src/disseminator/turbine.rs, src/lib.rs, src/network/simulated.rs, src/shredder.rs, src/slot.rs, tests/liveness.rs
Before, we stored the slot as a simple `u64` which is dangerous as it can be mixed up with other unrelated types.  This PR defines `Slot` as a `struct(u64)` to provide us with some type safety.
In general, I am not happy with the use of `SLOTS_PER_WINDOW` in so many tests.  But I am not sure if it makes sense to update them at this point in time.  We can discuss if we want to refactor them in this PR or a subsequent PR.
=> refactor: Introduce a Slot type

benches/disseminator.rs, benches/network.rs, benches/shredder.rs, src/consensus/blockstore.rs, src/consensus/produce_block.rs, src/disseminator/rotor.rs, src/disseminator/trivial.rs, src/disseminator/turbine.rs, src/network/simulated.rs, src/shredder.rs, src/shredder/reed_solomon.rs
Shredding a slice currently ends up cloning the slice.  So passing a reference to the slice to the function in effect hides this information at the type level.  Changing the API to consume the slice so that the callers know that this is an expensive operation.
=> refactor: bubble up `clone`

src/consensus.rs, src/consensus/votor.rs
This addresses #62 and fixes various minor problems with the timeouts:
=> fix: timeouts

src/consensus.rs, src/consensus/produce_block.rs, src/main.rs, src/shredder/reed_solomon.rs, src/slot.rs
Right now, simply running `./run.sh` crashes immediately.
This PR fixes all these and makes this simple local test run again.
=> fix: main/alpenglow binary crashes immediately

src/consensus.rs, src/consensus/blockstore.rs, src/consensus/pool.rs, src/consensus/pool/parent_ready_tracker.rs, src/consensus/pool/parent_ready_tracker/parent_ready_state.rs, src/consensus/pool/slot_state.rs, src/consensus/produce_block.rs, src/consensus/votor.rs, src/network/simulated/core.rs, src/slot.rs
This addresses #54.
Slot 0 will no longer contain leader proposed blocks, only the genesis block. Block production and voting loop should thus both skip over slot 0.
=> fix: cleaner genesis handling

benches/disseminator.rs, benches/network.rs, benches/shredder.rs, src/consensus/blockstore.rs, src/consensus/blockstore/slot_block_data.rs, src/consensus/produce_block.rs, src/disseminator/rotor.rs, src/disseminator/trivial.rs, src/disseminator/turbine.rs, src/lib.rs, src/network/simulated.rs, src/shredder.rs, src/shredder/reed_solomon.rs, src/slice.rs, src/test_utils.rs
Part of #4.  We now track parent in the slice separately from the actual data payload.  This will make it easier to indicate when a slice contains a parent or not.
=> feat: track parent separately in `Slice`

src/disseminator/turbine.rs, src/network.rs, src/network/simulated.rs, src/network/tcp.rs, src/network/udp.rs
Since we are already using `async_trait` in other places now, change stable use of `impl Future<...>` syntax to use of the `async_trait` crate for the `Network` trait as well.
=> refactor: use `async_trait` for `Network` trait

src/consensus/block_producer.rs
Optimistic block production was blocking on producing a slice with timeout duration `Duration::MAX` before the `ParentReady` event has been seen. If this slice never completed, e.g. because we don't see any transaction, we block forever and never start the blocktime timeout. The way I fixed this now, is by limiting the time per slice before `ParentReady` was seen to a maximum of `DELTA_BLOCK / 2`.
Closes #119.
=> fix: optimistic block production leading to skips

src/consensus.rs, src/consensus/block_producer.rs, src/consensus/votor.rs
This introduces the additional parameter `DELTA_FIRST_SLICE` a short timeout for producing the first slice. The leader makes sure to only take at most this amount of time for the first slice. In return, we can account for the crashed leader timeout correctly. See issue #65 for more info.
Closes #65.
=> fix: correctly account for first slice in crashed leader timeout

src/consensus/block_producer.rs
closes #121 
- Adds a test case for `produce_block_parent_not_ready`
- handles a couple of left over edge cases in optimistic handover
=> Adds a test for and handles some edge cases for optimistic handover

src/types/slot.rs
Part of https://github.com/qkniep/alpenglow/issues/135.
Previously, we would've wrapped around produced a bogus slot.
=> bug: panic instead of wrapping around in `Slot::prev()`

src/consensus/block_producer.rs, src/consensus/blockstore.rs, src/consensus/blockstore/slot_block_data.rs, src/repair.rs
=> refactor: rename `canonical` and `alternatives` to `disseminated` and `repaired`

src/crypto/merkle.rs, src/shredder.rs
Handles some open tasks in the `crypto::merkle` module. Some out-of-bounds accesses have assertions now. Also increased max number of leaves from 2^24 to 2^32, providing the efficient function used to calculate those.
Maybe most important, we now use the pre-calculated `EMPTY_ROOTS` to speed up the constructor (up to a factor of two if the second half of the tree is almost empty).
Closes #148.
=> feat: faster Merkle tree construction, more max nodes, handle edge cases

src/consensus/pool.rs, src/consensus/pool/slot_state.rs, src/disseminator/turbine.rs
Addresses some minor TODO comments. Most importantly, when standstill recovery kicks in, Pool now only sends one type of finalization for the last finalized slot. Instead of all certificates for that slot.
=> nit: handle some TODO comments

src/consensus/pool.rs, src/consensus/pool/finality_tracker.rs
Previously, the basically meaningless notion of a finalized slot without a block was wrongfully exposed and used (i.e. the case when we have a finalization cert but don't yet have the notarization cert for a block). This is now fixed, only exposing the notion of notarized block as having fast finalization or final+notar certs outside of `FinalityTracker`. To go along with this, some of the naming around finalization and certificates has been adapted to be more accurate and less error prone.
=> fix: finalization slot/block, naming around certs/finalization, adapt tests

src/all2all/robust.rs, src/all2all/trivial.rs, src/bin/node.rs, src/bin/performance_test.rs, src/consensus/block_producer.rs, src/consensus/blockstore.rs, src/consensus/cert.rs, src/disseminator/rotor.rs, src/disseminator/rotor/sampling_strategy.rs, src/disseminator/trivial.rs, src/disseminator/turbine.rs, src/lib.rs, src/main.rs, src/network.rs, src/network/simulated.rs, src/network/simulated/core.rs, src/network/simulated/stake_distribution.rs, src/network/tcp.rs, src/network/udp.rs, src/repair.rs, src/test_utils.rs, tests/liveness.rs
This makes things a bit more ergonomic; reduces string parsing when sending messages; etc.
=> refactor: use `SocketAddr` instead of `String` for storing addresses

src/consensus.rs, src/repair.rs
- `Repair` doesn't seem to use the tx side of the channel
- the rx side of the channel is only used in `repair_loop()` and it is `take`n out of the struct.  So instead of passing it into `new()` pass it into `repair_loop()`.
=> refactor: improvements to passing tokio channels to `Repair`

src/consensus/blockstore/slot_block_data.rs, src/shredder.rs
If we pass the cache btreemap `Entry` to `Shred::verify()`, it can update it when the checks pass, use it to skip some checks, and we consolidate some error checking.
=> refactor: Pass the btreemap `Entry` to `Shred::verify()` to consolidate updating the cache and error checking

src/consensus/blockstore/slot_block_data.rs, src/shredder.rs, src/shredder/reed_solomon.rs, src/shredder/validated_shred.rs
Part of https://github.com/qkniep/alpenglow/issues/85.
If `try_reconstruct_slice()` and `try_reconstruct_block()` fail, then propagate the error up the call stack to eventually call `try_skip_window()`.
In order to accomplish the above in a clean manner, the following changes are made:
- Introduces `ValidatedShred` which can only be constructed by verifying a shred.
- refactors `check_shred_to_add` and `add_valid_shred` so that the first function (`add_shred`) validates the shred and the second function (`add_validated_shred`) performs various checks, adds the shred, and calls `try_reconstruct_slice()` and `try_reconstruct_block()` as needed.
=> feat: propagate errors from slice and block reconstruction

benches/network.rs, src/all2all.rs, src/all2all/robust.rs, src/all2all/trivial.rs, src/bin/node.rs, src/bin/performance_test.rs, src/consensus.rs, src/consensus/votor.rs, src/lib.rs, src/network.rs, src/test_utils.rs
=> refactor: remove `NetworkMessage::Vote` and `NetworkMessage::Cert`

src/all2all/robust.rs, src/all2all/trivial.rs, src/consensus.rs, src/consensus/block_producer.rs, src/disseminator/rotor.rs, src/disseminator/trivial.rs, src/disseminator/turbine.rs, src/network.rs, src/repair.rs
Part of #187 
Closes #200 
Introduces some new traits that constrain the `Network` trait and uses them in various places.
=> refactor: use marker traits for different variants of `Network`

src/all2all/robust.rs, src/network/simulated/core.rs
In https://github.com/qkniep/alpenglow/pull/213, we observed some test failures.  Debugging it, I believe the following is happening:
- The sender is broadcasting and then exiting without receiving the messages that it broadcast
- if we send the messages too quickly as is happening in #213, the sender is exiting before simulated/core is able to deliver the msgs to it.
- the sender exits and then the core tries to send it message, finds that the channel is closed, and panics
- now the other receivers get stuck as they have not received all of the messages they wanted
The proposed fix is for the sender to receive messages that it broadcast before exiting and for the the core to not panic if it fails deliver messages.
=> bug: fix some broadcast test failures

Cargo.lock, Cargo.toml
several patch releases, including patch releases of the `aes` and `ctr` crates
=> nit: update deps

src/shredder.rs
=> nit: move `is_data()` and `is_coding()` to `Shred` and actually use them

src/shredder.rs, src/shredder/reed_solomon.rs
If we assume that:
- we will always have `DATA_SHREDS`
- the array of shreds will always put data shreds before coding shreds
We can simplify the API for `reed_solomon_shred()` and `reed_solomon_deshred()`.  It just needs to know how many of the shreds are coding.
Closes: #227
=> refactor: simply `reed_solomon_[de]shred()` api
