qkniep/alpenglow

Cargo.lock
Cargo.toml
src/bin/node.rs
src/bin/performance_test.rs
src/consensus.rs
src/consensus/blockstore.rs
src/consensus/produce_block.rs
src/lib.rs
src/main.rs
src/network.rs
tests/liveness.rs

When producing slices, we actually try to receive transactions from users to include into the slice.

feat: receive txs from user when producing blocks

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
src/all2all/robust.rs
src/all2all/trivial.rs
src/bin/all2all_test.rs
src/bin/performance_test.rs
src/bin/simulations/latency.rs
src/bin/simulations/rotor_safety.rs
src/consensus.rs
src/consensus/pool.rs
src/consensus/pool/slot_state.rs
src/consensus/produce_block.rs
src/consensus/votor.rs
src/crypto/aggsig.rs
src/disseminator/rotor.rs
src/disseminator/rotor/sampling_strategy.rs
src/disseminator/turbine.rs
src/main.rs
src/network/simulated.rs
src/network/simulated/core.rs
src/repair.rs
src/shredder.rs
src/test_utils.rs

Part of https://github.com/qkniep/alpenglow/issues/34.
This only enables an initial set of lints.  We probably want to expand which other set we would like to have.

chore: a bunch of clippy related fixes and enable it on CI

---

src/bin/all2all_test.rs
src/bin/node.rs
src/bin/performance_test.rs
src/bin/simulations/main.rs
src/lib.rs
src/logging.rs
src/main.rs

Hello, I was going through and I saw this low hanging fruit. I hope I did a welcome thing by contributing with this. any comment or request is welcome of course!

refactored out logforth

---

src/consensus.rs
src/consensus/blockstore.rs
src/consensus/blockstore/slot_block_data.rs
src/consensus/produce_block.rs
src/repair.rs

feat: extend blockstore to store more than one block per slot

---

src/consensus.rs
src/consensus/pool.rs
src/consensus/pool/parent_ready_tracker.rs
src/consensus/pool/parent_ready_tracker/parent_ready_state.rs
src/lib.rs

Part of #4 
Adds the ability to be able to `await` for `ParentReady`.

feat: make waiting for `ParentReady` `await`able

---

.github/workflows/rust.yml

Add code coverage to the CI workflow and upload it to [codecov.io](https://codecov.io).

ci: add codecov

---

src/consensus/pool.rs

tests: add tests for `add_vote` and `add_cert` failure cases in Pool

---

src/disseminator/rotor/sampling_strategy.rs
tests/liveness.rs

This addresses #51 and fixes broken liveness tests.

fix: slow tests

---

.github/workflows/rust.yml
src/crypto/aggsig.rs
src/crypto/hash.rs
src/crypto/signature.rs

refactor: add more tests to `crypto` module

---

src/network/simulated/ping_data.rs
src/network/simulated/stake_distribution.rs

refactor: add more tests to `network/simulated` module

---

src/disseminator/rotor/sampling_strategy.rs

refactor: add more tests to `sampling_strategy` module

---

src/consensus/blockstore.rs

I am doing some debugging and I find it cumbersome to have to type `Slot::new()` often.  No big deal if you prefer the existing style.

nit: fewer usage of `Slot::new()` in test code

---

src/consensus.rs

This is mainly me trying to improve my understanding of mockall.

test: another simple test for `wait_for_first_slot`

---

src/logging.rs

test: add trivial test to `logging` module

---

src/consensus/block_producer.rs
src/disseminator.rs
src/disseminator/rotor.rs
src/disseminator/trivial.rs
src/disseminator/turbine.rs

Additionally adds `async_trait` and `automock` on `Disseminator`.

test: adds a test for `shred_and_disseminate()`

---

src/consensus/block_producer.rs
src/consensus/blockstore/slot_block_data.rs

Closes #4.
Final bits of optimistic handover.  The leader switches the parent and when reconstructing the block, we check for the updated parent.

feat: final bits of optimistic handover

---

src/consensus/block_producer.rs

fix: underflow when calculating block production timeouts

---

src/consensus/pool/parent_ready_tracker.rs

I messed up when merging #134 and forgot to push the last commit. So, here are some more comments in `ParentReadyTracker`.

nit: add comments

---

Cargo.toml

nit: enable overflow checking in release builds

---

.github/workflows/rust.yml

ci: introduce timeouts

---

src/repair.rs
test.sh

Closes https://github.com/qkniep/alpenglow/issues/165

test: run `repair_large_block` in release mode only

---

tests/liveness.rs

Introduces a struct to help track which network is for which component and not having to do a lot of indexing into `Vec` or `pop`ing from a `VecDeque` in the right order.

refactor: improvements to how the networks are initialized in `liveness::create_test_nodes()`

---

benches/network.rs
src/bin/node.rs
src/bin/performance_test.rs
src/disseminator/rotor.rs
src/disseminator/trivial.rs
src/disseminator/turbine.rs
src/lib.rs
src/network.rs
src/network/simulated.rs

refactor: remove `NetworkMessage::Shred`
